"""Generate ARCHITECTURE.md from a CodebaseProfile."""

from __future__ import annotations

from codebase_archaeologist.generators.base import BaseGenerator


class ArchitectureGenerator(BaseGenerator):
    """Generates an ARCHITECTURE.md document from analysis results."""

    def generate(self) -> str:
        """Return full ARCHITECTURE.md content as a string."""
        sections = [
            self._header(),
            self._tech_stack(),
            self._directory_structure(),
            self._entry_points(),
            self._architecture_patterns(),
            self._code_quality_metrics(),
            self._hot_files(),
            self._knowledge_risks(),
        ]
        return "\n\n".join(section for section in sections if section) + "\n"

    # ── Section helpers ──────────────────────────────────────────────

    def _header(self) -> str:
        project_name = self.profile.name or "Unknown Project"
        return (
            f"# Architecture — {project_name}\n\n> Auto-generated by Codebase Archaeologist v0.1.0"
        )

    def _tech_stack(self) -> str:
        rows: list[str] = []
        cs = self.profile.code_structure
        deps = self.profile.dependencies

        # Primary language
        if cs.primary_language and cs.primary_language != "unknown":
            version = deps.python_version if cs.primary_language == "Python" else ""
            rows.append(self._table_row("Language", cs.primary_language, version))

        # Framework
        if deps.framework:
            rows.append(self._table_row("Framework", deps.framework, deps.framework_version))

        # Key dependencies by category
        for category, dep_names in sorted(deps.tech_categories.items()):
            label = category.capitalize()
            for name in dep_names:
                version = self._find_dep_version(name)
                rows.append(self._table_row(label, name, version))

        # Package manager
        if deps.package_manager:
            rows.append(self._table_row("Package Manager", deps.package_manager, ""))

        # CI system
        if cs.has_ci and cs.ci_system:
            rows.append(self._table_row("CI", cs.ci_system, ""))

        if not rows:
            return ""

        header = "## Tech Stack\n\n| Category | Technology | Version |\n| --- | --- | --- |"
        return header + "\n" + "\n".join(rows)

    def _directory_structure(self) -> str:
        tree = self.profile.code_structure.directory_tree
        if not tree:
            return ""

        lines = ["## Directory Structure\n\n```"]
        project_name = self.profile.name or "repo"
        lines.append(f"{project_name}/")

        for directory in sorted(tree.keys()):
            # Show top-level directories
            indent = "  "
            lines.append(f"{indent}{directory}/")
            # Show one level of files inside each directory
            for item in sorted(tree[directory]):
                lines.append(f"{indent}  {item}")

        lines.append("```")
        return "\n".join(lines)

    def _entry_points(self) -> str:
        entry_points = self.profile.code_structure.entry_points
        if not entry_points:
            return ""

        lines = ["## Entry Points\n"]
        for ep in entry_points:
            desc = f" — {ep.description}" if ep.description else ""
            lines.append(f"- **{ep.type}**: `{ep.path}`{desc}")

        return "\n".join(lines)

    def _architecture_patterns(self) -> str:
        patterns = self.profile.patterns.architecture_patterns
        if not patterns:
            return ""

        descriptions: dict[str, str] = {
            "layered": "Separation into distinct layers (presentation, logic, data).",
            "mvc": "Model-View-Controller separation of concerns.",
            "hexagonal": "Ports and adapters — core decoupled from externals.",
            "microservices": "Independent, deployable services over network.",
            "monolith": "Single deployable unit containing all functionality.",
            "event-driven": "Components communicate through asynchronous events.",
            "plugin": "Core system extended through dynamically loadable plugins.",
            "cqrs": "Command Query Responsibility Segregation — separate read and write models.",
        }

        lines = ["## Architecture Patterns\n"]
        for pattern in patterns:
            explanation = descriptions.get(pattern.lower(), "Detected pattern.")
            lines.append(f"- **{pattern}**: {explanation}")

        return "\n".join(lines)

    def _code_quality_metrics(self) -> str:
        p = self.profile.patterns
        lines = [
            "## Code Quality Metrics\n",
            f"- Type hint coverage: {p.type_hint_ratio:.0%}",
            f"- Docstring coverage: {p.docstring_ratio:.0%}",
            f"- Average function length: {p.avg_function_length:.1f} lines",
        ]
        return "\n".join(lines)

    def _hot_files(self) -> str:
        git = self.profile.git_history
        if git.total_commits == 0 or not git.hot_files:
            return ""

        lines = [
            "## Hot Files\n",
            "| File | Changes | Contributors |",
            "| --- | --- | --- |",
        ]

        top_files = git.hot_files[:10]
        for hf in top_files:
            lines.append(f"| `{hf.path}` | {hf.change_count} | {hf.unique_contributors} |")

        lines.append("")
        lines.append("> These files change frequently and may need extra attention during reviews.")
        return "\n".join(lines)

    def _knowledge_risks(self) -> str:
        git = self.profile.git_history
        if git.total_commits == 0:
            return ""

        lines = ["## Knowledge Risks\n"]

        # Bus factor
        bf = git.bus_factor
        lines.append(
            f"- **Bus factor: {bf}** — the minimum number of contributors who would "
            "need to leave before critical knowledge is lost."
        )
        if bf <= 1:
            lines.append(
                "  - **Critical: Single point of failure.** "
                "Consider cross-training or pairing on key areas."
            )

        # Files with single contributor
        solo_files = [hf.path for hf in git.hot_files if hf.unique_contributors == 1]
        if solo_files:
            lines.append("")
            lines.append("**Files with only 1 contributor:**\n")
            for path in solo_files:
                lines.append(f"- `{path}`")

        return "\n".join(lines)

    # ── Internal utilities ───────────────────────────────────────────

    @staticmethod
    def _table_row(category: str, technology: str, version: str) -> str:
        return f"| {category} | {technology} | {version} |"

    def _find_dep_version(self, name: str) -> str:
        """Look up a dependency's version constraint from both dep lists."""
        for dep in self.profile.dependencies.dependencies:
            if dep.name == name:
                return dep.version_constraint
        for dep in self.profile.dependencies.dev_dependencies:
            if dep.name == name:
                return dep.version_constraint
        return ""
