"""Generate ONBOARDING.md from a CodebaseProfile."""

from __future__ import annotations

from codebase_archaeologist.generators.base import BaseGenerator
from codebase_archaeologist.models import CodebaseProfile


class OnboardingGenerator(BaseGenerator):
    """Generate a developer onboarding guide from analyzed codebase data."""

    def __init__(self, profile: CodebaseProfile) -> None:
        super().__init__(profile)

    def generate(self) -> str:
        """Return full ONBOARDING.md content as a markdown string."""
        sections: list[str] = [
            self._build_header(),
            self._build_quick_start(),
        ]

        directory_section = self._build_project_structure()
        if directory_section:
            sections.append(directory_section)

        conventions_section = self._build_conventions()
        if conventions_section:
            sections.append(conventions_section)

        sections.append(self._build_where_to_start())

        contributors_section = self._build_contributors()
        if contributors_section:
            sections.append(contributors_section)

        patterns_section = self._build_common_patterns()
        if patterns_section:
            sections.append(patterns_section)

        return "\n".join(sections) + "\n"

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _build_header(self) -> str:
        """Build the document header."""
        name = self.profile.name or "Unnamed Project"
        lines = [
            f"# Onboarding Guide — {name}",
            "",
            "> Auto-generated by Codebase Archaeologist v0.1.0",
            "",
            f"Welcome to {name}! This guide will help you get up to speed quickly.",
            "",
        ]
        return "\n".join(lines)

    def _build_quick_start(self) -> str:
        """Build the Quick Start section with setup, test, and lint commands."""
        structure = self.profile.code_structure
        deps = self.profile.dependencies

        primary_language = structure.primary_language or "unknown"
        python_version = deps.python_version
        package_manager = deps.package_manager or "unknown"

        # Prerequisites
        prereq_parts = [f"- {primary_language}"]
        if python_version:
            prereq_parts[0] += f" {python_version}"
        prereq_parts.append(f"- {package_manager}")

        # Infer commands
        install_cmd = self._infer_install_command()
        test_cmd = self._infer_test_command()
        lint_cmd = self._infer_lint_command()

        lines = [
            "## Quick Start",
            "",
            "### Prerequisites",
            *prereq_parts,
            "",
            "### Setup",
            "```bash",
            "# Clone and install",
            "git clone <repo-url>",
            f"cd {self.profile.name or 'project'}",
            install_cmd,
            "```",
            "",
            "### Run Tests",
            "```bash",
            test_cmd,
            "```",
            "",
            "### Run Linter",
            "```bash",
            lint_cmd,
            "```",
            "",
        ]
        return "\n".join(lines)

    def _build_project_structure(self) -> str:
        """Build the Project Structure section from the directory tree."""
        directory_tree = self.profile.code_structure.directory_tree
        if not directory_tree:
            return ""

        lines = [
            "## Project Structure",
            "",
        ]

        for directory, files in sorted(directory_tree.items()):
            lines.append(f"- **`{directory}`** — {self._describe_directory(directory)}")
            for f in sorted(files):
                lines.append(f"  - `{f}`")

        lines.append("")
        return "\n".join(lines)

    def _build_conventions(self) -> str:
        """Build the Coding Conventions section."""
        patterns = self.profile.patterns

        no_data = (
            not patterns.naming_conventions
            and patterns.type_hint_ratio == 0.0
            and patterns.docstring_ratio == 0.0
        )
        if no_data:
            return ""

        lines = [
            "## Coding Conventions",
            "",
        ]

        for conv in patterns.naming_conventions:
            examples_str = ", ".join(conv.examples) if conv.examples else "N/A"
            lines.append(f"- **{conv.name}**: `{conv.pattern}` (examples: {examples_str})")

        if patterns.type_hint_ratio > 0.0:
            pct = int(patterns.type_hint_ratio * 100)
            lines.append(f"- Type hints: used in {pct}% of functions")

        if patterns.docstring_ratio > 0.0:
            pct = int(patterns.docstring_ratio * 100)
            lines.append(f"- Docstrings: present in {pct}% of functions")

        lines.append("")
        return "\n".join(lines)

    def _build_where_to_start(self) -> str:
        """Build the Where to Start Reading section."""
        structure = self.profile.code_structure
        deps = self.profile.dependencies

        lines = [
            "## Where to Start Reading",
            "",
        ]

        # Entry points
        if structure.entry_points:
            for ep in structure.entry_points:
                desc = ep.description or ep.type
                lines.append(f"- Start with `{ep.path}` — {desc}")
        else:
            lines.append("- Look at the root directory for main entry points")

        # Framework hint
        if deps.framework:
            lines.append(f"- This is a **{deps.framework}** project")

        # Test directory
        if structure.has_tests and structure.test_directory:
            lines.append(f"- Tests are in `{structure.test_directory}`")
        elif structure.has_tests:
            lines.append("- Tests are in `tests/`")

        lines.append("")
        return "\n".join(lines)

    def _build_contributors(self) -> str:
        """Build the Key Contributors section."""
        contributors = self.profile.git_history.contributors
        if not contributors:
            return ""

        lines = [
            "## Key Contributors",
            "",
            "| Name | Commits | Focus Areas |",
            "|------|---------|-------------|",
        ]

        for c in contributors:
            focus = ", ".join(c.files_touched[:3]) if c.files_touched else "N/A"
            lines.append(f"| {c.name} | {c.commit_count} | {focus} |")

        lines.extend(
            [
                "",
                "Reach out to these people for domain knowledge.",
                "",
            ]
        )
        return "\n".join(lines)

    def _build_common_patterns(self) -> str:
        """Build the Common Patterns section."""
        patterns = self.profile.patterns

        if not patterns.architecture_patterns and not patterns.test_patterns:
            return ""

        lines = [
            "## Common Patterns",
            "",
        ]

        if patterns.architecture_patterns:
            lines.append("### Architecture")
            for p in patterns.architecture_patterns:
                lines.append(f"- {p}")
            lines.append("")

        if patterns.test_patterns:
            lines.append("### Testing")
            for p in patterns.test_patterns:
                lines.append(f"- {p}")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Inference helpers
    # ------------------------------------------------------------------

    def _infer_install_command(self) -> str:
        """Infer the install command from package manager."""
        pm = self.profile.dependencies.package_manager
        if pm == "pip":
            return 'pip install -e ".[dev]"'
        if pm == "npm":
            return "npm install"
        if pm == "cargo":
            return "cargo build"
        if pm == "poetry":
            return "poetry install"
        return "# install dependencies"

    def _infer_test_command(self) -> str:
        """Infer the test command from dev dependencies."""
        for dep in self.profile.dependencies.dev_dependencies:
            if dep.name == "pytest":
                return "pytest"
            if dep.name == "jest":
                return "npx jest"
            if dep.name == "vitest":
                return "npx vitest"
            if dep.name == "mocha":
                return "npx mocha"

        pm = self.profile.dependencies.package_manager
        if pm == "npm":
            return "npm test"
        if pm == "cargo":
            return "cargo test"
        return "# run tests"

    def _infer_lint_command(self) -> str:
        """Infer the lint command from dev dependencies."""
        for dep in self.profile.dependencies.dev_dependencies:
            if dep.name == "ruff":
                return "ruff check . && ruff format ."
            if dep.name == "flake8":
                return "flake8 ."
            if dep.name == "pylint":
                return "pylint src/"
            if dep.name == "eslint":
                return "npx eslint ."
            if dep.name == "biome":
                return "npx biome check ."
        return "# run linter"

    def _describe_directory(self, directory: str) -> str:
        """Return a brief description for a directory based on its name."""
        descriptions: dict[str, str] = {
            "src/": "source code",
            "tests/": "test suite",
            "docs/": "documentation",
            ".github/": "GitHub configuration (CI, issue templates)",
            "scripts/": "utility scripts",
            "config/": "configuration files",
            "lib/": "library code",
            "bin/": "executables",
        }
        for key, desc in descriptions.items():
            if directory.startswith(key) or directory == key:
                return desc
        return "project files"
